package com.ecol.authService.enums;

public enum UserRole {
    SUPER_ADMIN,
    ADMIN,

    HEAD_OF_DEPARTMENT,
    ACADEMIC_DIRECTOR,
    VICE_PRINCIPAL,
    REGISTRAR,
    BURSAR,
    ACCOUNTANT,
    FINANCE_MANAGER,

    HR_MANAGER,
    HR_OFFICER,
    PAYROLL_OFFICER,

    ADMISSIONS_OFFICER,
    EXAM_OFFICER,

    LIBRARIAN,
    ASSISTANT_LIBRARIAN,

    LAB_MANAGER,
    LAB_TECHNICIAN,

    ICT_MANAGER,
    IT_SUPPORT,
    SYSTEM_ADMIN,
    NETWORK_ADMIN,

    SECURITY_OFFICER,

    PROCUREMENT_OFFICER,
    STORE_KEEPER,

    HOSTEL_MANAGER,
    HOSTEL_WARDEN,

    TRANSPORT_MANAGER,
    DRIVER,

    NURSE,
    SCHOOL_DOCTOR,
    COUNSELOR,

    RECEPTIONIST,
    SECRETARY,

    PUBLIC_RELATIONS_OFFICER,

    QUALITY_ASSURANCE_MANAGER,
    QUALITY_ASSURANCE_OFFICER,

    COMPLIANCE_OFFICER,
    LEGAL_OFFICER,

    MARKETING_MANAGER,

    EVENT_COORDINATOR,

    SPORTS_DIRECTOR,
    SPORTS_COACH,

    DEAN_OF_STUDIES,
    DISCIPLINE_MASTER,

    CLASS_COORDINATOR,
    TIMETABLE_OFFICER,
    STUDENT,
    CURRICULUM_MANAGER,

    ALUMNI_COORDINATOR,

    RESEARCH_COORDINATOR,

    TRAINING_COORDINATOR,

    FACILITIES_MANAGER,
    MAINTENANCE_SUPERVISOR
}