spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  config:
    import: optional:file:.env.properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

cors:
  allowed-origins: ${FRONTEND_DOMAINS}
  allowed-methods: ${ALLOWED_METHODS}

api:
  version: ${API_VERSION}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}
  magic-link-expiration-ms: ${JWT_MAGIC_LINK_EXPIRATION_TOKEN_MS}

swagger:
  server:
    local: http://localhost:8080
    prod: https://api.courseservice.com

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  info:
    env:
      enabled: true

http:
  client:
    connect-timeout: 10s
    read-timeout: 120s

logging:
  level:
    org.springframework.boot.context: DEBUG
    org.springframework.boot.web.embedded.tomcat: INFO
    org.springframework.boot.web.servlet.context: INFO
    org.springframework.context: INFO

firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  client-id: ${FIREBASE_CLIENT_ID}

openai:
  api-key: ${GROQ_API_KEY}
  model: llama-3.3-70b-versatile
  temperature: 0.4
  max-tokens: 2000
  base-url: https://api.groq.com/openai/v1